// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brrwhtawjqzszxkpkqhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycndodGF3anF6c3p4a3BrcWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDkzNjQsImV4cCI6MjA3MzIyNTM2NH0.LqMSGqs1Tifx9Kq_OFIeZvW1gG7JDiFKZag076bsnI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});